theme: jekyll-theme-cayman
title: Web Shoulders Technologies
description: Web Shoulders Technologies is the business name under which [Parbhat Puri](https://parbhatpuri.com/) runs his Software Consulting business and [Remote Inning](https://www.remoteinning.com/).
show_downloads: false
