theme: jekyll-theme-cayman
title: Web Shoulders Technologies
description: Web Shoulders Technologies is the business name under which Parbhat Puri runs his Software Consulting business and Remote Inning.
show_downloads: false
